version: "3"
services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443" 
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
    networks:
      - network
    restart: always
  mariadb:
    build: 
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    container_name: mariadb
    volumes:
      - db-vol:/var/lib/mysql
    restart: always
    env_file:
      - .env
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  db-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./mariadb-data


#  nginx:
#    build:
#      context: .
#      dockerfile: requirements/nginx/Dockerfile
# services:
#   nginx:
#     build:
#       context: .
#       dockerfile: requirements/nginx/Dockerfile
#   container_name: nginx
#   port: 
#     - "443:443"
#   volumes:
#     - requirements/nginx/conf/nginx.conf:/etc/nginx/conf.d/nginx.conf #TODO 記事見ながらとりあえずかいただけなのであっとるかわからんため後で確認
#   restart: always
#   depends_on:
#     - wordpress


