version: "3"
services:
<<<<<<< HEAD
=======
  debian:
    image: debian:latest
    tty: true
    restart : always
    container_name: inception
    ports:
      - "443:443"
>>>>>>> 1caecb7344141d31063a5366f5007a773e88f2b9
  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - pages:/var/www/html
    networks:
      - network
    restart: always

networks:
  network:
    driver: bridge

volumes:
  pages:

#  nginx:
#    build:
#      context: .
#      dockerfile: requirements/nginx/Dockerfile
# services:
#   nginx:
#     build:
#       context: .
#       dockerfile: requirements/nginx/Dockerfile
#   container_name: nginx
#   port: 
#     - "443:443"
#   volumes:
#     - requirements/nginx/conf/nginx.conf:/etc/nginx/conf.d/nginx.conf #TODO 記事見ながらとりあえずかいただけなのであっとるかわからんため後で確認
#   restart: always
#   depends_on:
#     - wordpress


